### ISSUE TITLE
Improve code quality

### ISSUE THREAD

**Issue by stweil** [cisocrgroup/ocrd_cis#21]
[LGTM](https://lgtm.com/projects/g/cisocrgroup/ocrd_cis/) shows only a moderate C code quality for `ocrd_cis` and gives numerous hints how it could be improved.

**Comment by finkf** [comment]
Thank you, I will have a look on this, after we have incorporated all other changes.

**Comment by finkf** [comment]
[LGTM](https://lgtm.com/projects/g/cisocrgroup/ocrd_cis/?mode=list) Code Quality: A.
