### ISSUE TITLE
Line detection during dewarping is defective

### ISSUE THREAD

**Issue by wrznr** [cisocrgroup/ocrd_cis#32]
`ocrd-cis-ocropy-dewarp` frequently complains about finding more than one text line in a line segment:
```
09:11:12.258 INFO processor.OcropyDewarp - About to dewarp page 'Page1' region 'Page1_Block16' line 'Page1_Block16_line0007'
09:11:12.273 ERROR processor.OcropyDewarp - cannot dewarp line "Page1_Block16_line0007": found more than 1 textline, most likely from bad cropping
```
The corresponding lines however look perfectly fine:
![FILE_0011_ARESEG-IMG_Page1_Block16_Page1_Block16_line0007](https://user-images.githubusercontent.com/26707219/70508014-d6d54200-1b2d-11ea-88c0-51feb0a2453d.png)

@bertsky Is it possible to adjust the internal heuristics to be more lax here?

**Comment by bertsky** [comment]
There is a [parameter](https://github.com/cisocrgroup/ocrd_cis/blob/2445bff44e856f8015f38bdbca59c8705ad0efa0/ocrd_cis/ocropy/ocrolib/lineest.py#L27), but it is not exposed in the tool json. The problem here is most likely the horizontal line above `Beachtung`. But I'd have to check the interim results in ocrolib.lineest.check...

**Comment by bertsky** [comment]
> The problem here is most likely the horizontal line above `Beachtung`

Confirmed:

![lineest-32 check-counts](https://user-images.githubusercontent.com/38561704/70576904-fb6b0180-1ba1-11ea-8ad9-23de1fdedb20.png)

This tells you that the 106 foreground pixels in that horizontal line make up slightly more than 2 percent (the default `max_ignore`) of the total foreground pixels. Here is how it would have looked when applying the measured centerline:

![lineest-32 dew](https://user-images.githubusercontent.com/38561704/70577401-1f7b1280-1ba3-11ea-9fd2-94e3efc6bbe0.png)

This should be perfectly usable, so the check is definitely overreacting here. 

But what if the same percentage of intruding foreground pixels is distributed more maliciously? I am hesitant to change the default threshold. Do you want me to expose this parameter?

**Comment by bertsky** [comment]
@wrznr you can try this out [here](https://github.com/bertsky/ocrd_cis/tree/dewarp-expose-check-threshold). I have not tested this yet. When we are both satisfied, I will turn this into a PR.

**Comment by wrznr** [comment]
As much as I like parameterization, I do not see a chance that such fine-grained settings are possible in a mass digitization scenario. What would be an example for a “more malicious distribution”?

**Comment by bertsky** [comment]
> What would be an example for a “more malicious distribution”?

I remember seeing them – hence the small default threshold of only 2%. But all I could come up with were examples with very large ratios of intruders (>10%) which of course exhibited highly destructive dewarping and examples with very small ratios (<4%) which all proved to be still beneficial:

![OCR-D-IMG-RESEG-extract_0005_TextRegion_1476106017454_319_tl_34 bin](https://user-images.githubusercontent.com/38561704/70763494-2ee98f80-1d4c-11ea-8f74-1d0f5b5f3b4c.png)
![OCR-D-IMG-RESEG-extract_0005_TextRegion_1476106017454_319_tl_33 bin](https://user-images.githubusercontent.com/38561704/70763791-47a67500-1d4d-11ea-9ff0-3163695b93d7.png)
![OCR-D-IMG-RESEG-extract_0004_r_3_1_tl_3 bin](https://user-images.githubusercontent.com/38561704/70763934-c6031700-1d4d-11ea-80f5-fcb83091e116.png)
![OCR-D-IMG-RESEG-extract_0003_r_5_2_tl_6 bin](https://user-images.githubusercontent.com/38561704/70764060-31e57f80-1d4e-11ea-8771-bda476a3f5f9.png)
![OCR-D-IMG-RESEG-extract_0002_TextRegion_1476103196660_228_tl_2 bin](https://user-images.githubusercontent.com/38561704/70764180-a4eef600-1d4e-11ea-9c36-f0be6284fab0.png)
![OCR-D-IMG-RESEG-extract_0001_TextRegion_1476102552414_210_tl_2 bin](https://user-images.githubusercontent.com/38561704/70764243-debffc80-1d4e-11ea-8141-8f324856ee4d.png)


![Figure_1](https://user-images.githubusercontent.com/38561704/70763736-0f9f3200-1d4d-11ea-90ff-16e76db0fe1c.png)
![Figure_1](https://user-images.githubusercontent.com/38561704/70763815-5b51db80-1d4d-11ea-9a24-ce19fab53975.png)
![Figure_1](https://user-images.githubusercontent.com/38561704/70763929-bedc0900-1d4d-11ea-88aa-a61da4570122.png)
![Figure_1](https://user-images.githubusercontent.com/38561704/70764073-3e69d800-1d4e-11ea-8ce6-808dd8ebdb6d.png)
![Figure_1](https://user-images.githubusercontent.com/38561704/70764168-9e607e80-1d4e-11ea-9b7f-e1a5c640b12e.png)
![Figure_1](https://user-images.githubusercontent.com/38561704/70764251-e67fa100-1d4e-11ea-8680-a8a171ab3bf5.png)

So at least I should increase that threshold to (say) 5%.

> As much as I like parameterization, I do not see a chance that such fine-grained settings are possible in a mass digitization scenario.

It's not a must. We have defaults for that. So far we only had 1 parameter (`range=4`, from the internal Ocropy default – this is directly responsible for the average vertical padding). This change would add a second one:

```JSON
"parameters": {
  "range": {
   "type": "number",
   "format": "float",
   "description": "maximum vertical disposition or maximum margin (will be multiplied by mean centerline deltas to yield pixels)",
   "default": 4.0
  },
  "max_neighbour": {
   "type": "number",
   "format": "float",
   "description": "maximum rate of foreground pixels intruding from neighbouring lines (line will not be processed above that)",
   "default": 0.05
  }
 }
```
