### ISSUE TITLE
ocrd-cis-post-correct.sh is not OCR-D ready

### ISSUE THREAD

**Issue by VolkerHartmann** [cisocrgroup/ocrd_cis#40]
There seems to be a mix-up of input and output groups.
ocrd-cis-post-correct.sh -m mets.xml -p anyFile -I OCR-D-GT-SEG-BLOCK,OCR-D-GT-SEG-PAGE -O newOutputGorup 
Exception: Invalid input/output file grps:
	Output fileGrp[@USE='OCR-D-GT-SEG-BLOCK'] already in METS!

**Comment by VolkerHartmann** [comment]
For the parameters  '-J' and '--help' all other parameters must also be set which is not very helpful. ;-)

**Comment by finkf** [comment]
I will fix this ASAP. Thanks for reporting this issue.

**Comment by finkf** [comment]
I have a fix coming up that addresses this issue. The fix will also fix #42

**Comment by finkf** [comment]
fixed in 34201b6d00216d650b3d8759c1891dc6d9d1ce64

**Comment by VolkerHartmann** [comment]
:+1: Thanks. Works now fine for me.
