### ISSUE TITLE
ocrd-cis-ocropy-segment default level-of-operation

### ISSUE THREAD

**Issue by mikegerber** [cisocrgroup/ocrd_cis#81]
Should ocrd-cis-ocropy-segment have a default `level-of-operation` of `page`? (Currently it does not have this default)

**Comment by bertsky** [comment]
Not sure. For one, keeping the default at `region` ensures backwards compatibility of workflows. Also, the page segmentation algorithm is a completely new thing not associated to the old Ocropus segmenter (it just builds upon the flat line segmentation). So it's not something you would _expect_ from ocropy-segment.

**Comment by mikegerber** [comment]
I was expecting it to do segmentation of document pages.

**Comment by bertsky** [comment]
> I was expecting it to do segmentation of document pages.

Sure, if you don't know Ocropy usually only gave a single block per
page, and did not use that processor before #47, you might not have that
expectation.

So you think this is a documentation issue? (README and docstring /
`--help` text are fairly explicit about this...)
