### ISSUE TITLE
Core dump in ocrd-cis-ocropy-denoise

### ISSUE THREAD

**Issue by stefanCCS** [cisocrgroup/ocrd_cis#90]
With an update of `ocrd_all` from 22.03.22 I get this core dump:

```
ocrd-cis-ocropy-denoise -I OCR-D-BIN-REG -O OCR-D-BIN-REG-DENOISE -P level-of-operation region
08:45:41.815 INFO processor.OcropyDenoise - INPUT FILE 0 / P_4074_007817778_00001
08:45:42.493 INFO processor.OcropyDenoise - Page "OCR-D-BIN-REG-4074_007817778_00001" uses 200.000000 DPI
08:45:42.564 INFO processor.OcropyDenoise - About to despeckle 'OCR-D-BIN-REG-DENOISE-4074_007817778_00001_TR-1'
Segmentation fault (core dumped)
```

Maybe this is related to  #89

**Comment by bertsky** [comment]
Thanks @stefanCCS, that clue led me in the right direction. Yes, same cause as #89.

It's a [bug in OpenCV](https://github.com/opencv/opencv/issues/21366), which has been fixed upstream, but no release yet.

**Comment by bertsky** [comment]
Can you please try again with the most recent version of #87?

**Comment by stefanCCS** [comment]
> Can you please try again with the most recent version of #87?

Tested - is ok!

**Comment by stefanCCS** [comment]
Works ok in https://github.com/OCR-D/ocrd_all/releases/tag/v2022-05-04
