### ISSUE TITLE
Strange behaviour with symbolic links

### ISSUE THREAD

**Issue by stefanCCS** [cisocrgroup/ocrd_cis#92]
Version used: https://github.com/OCR-D/ocrd_all/releases/tag/v2022-05-04 
If you have an workspace, which has symbolic links in Image Source Folder (OCR-D-IMG), then it looks like that the command
`ocrd-cis-ocropy-binarize`
creates an copy for this image additional to the symbolic link.

It looks like to be the same issue, as also was here:
https://github.com/OCR-D/core/issues/802 
--> Please look for further details there.

**Comment by bertsky** [comment]
It is in fact the same issue – Ocropy does nothing special here, just uses the std functions from core. Closing here to keep it simple.
